const GET_ALL_RECIPES = 'GET_ALL_RECIPES';
const GET_ALL_DIETS = 'GET_ALL_DIETS';
const RECIPE_DETAIL = 'RECIPE_DETAIL';
const SEARCH_RECIPES = 'SEARCH_RECIPES';
const FILTER_BY_DIETS = 'FILTER_BY_DIETS';
const FILTER_BY_ORIGIN = 'FILTER_BY_ORIGIN';

module.exports = {
    GET_ALL_RECIPES,
    GET_ALL_DIETS,
    RECIPE_DETAIL,
    SEARCH_RECIPES,
    FILTER_BY_DIETS,
    FILTER_BY_ORIGIN
}